import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import {
  applyFixToPR,
  createPRWithFix,
  listOpenPRs,
  createOctokit,
  parseGitHubUrl,
} from "@/lib/github";
import type { TicketDraftFields } from "@/lib/schemas";

// GET /api/reports/[id]/fix-github - List open PRs for a repository
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const token = request.headers.get("x-github-token");
    const repoUrl = searchParams.get("repo");

    if (!token) {
      return NextResponse.json(
        { error: "GitHub token is required. Pass it in x-github-token header." },
        { status: 401 }
      );
    }

    if (!repoUrl) {
      return NextResponse.json(
        { error: "Repository URL or owner/repo is required" },
        { status: 400 }
      );
    }

    const parsed = parseGitHubUrl(repoUrl);
    if (!parsed) {
      return NextResponse.json(
        { error: "Invalid repository URL format. Use https://github.com/owner/repo or owner/repo" },
        { status: 400 }
      );
    }

    const octokit = createOctokit(token);
    const prs = await listOpenPRs(octokit, parsed.owner, parsed.repo);

    return NextResponse.json({ prs, owner: parsed.owner, repo: parsed.repo });
  } catch (error) {
    console.error("Error listing PRs:", error);
    const message = error instanceof Error ? error.message : "Failed to list PRs";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// POST /api/reports/[id]/fix-github - Apply fix to existing PR or create new PR
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await request.json();
    const token = request.headers.get("x-github-token");

    const {
      owner,
      repo,
      prNumber,
      createNewPR,
      componentPath,
      fixedCode,
      branchName,
    } = body;

    if (!token) {
      return NextResponse.json(
        { error: "GitHub token is required. Pass it in x-github-token header." },
        { status: 401 }
      );
    }

    if (!owner || !repo) {
      return NextResponse.json(
        { error: "Owner and repo are required" },
        { status: 400 }
      );
    }

    if (!componentPath || !fixedCode) {
      return NextResponse.json(
        { error: "componentPath and fixedCode are required" },
        { status: 400 }
      );
    }

    // Get report with draft for commit message context
    const report = await prisma.report.findUnique({
      where: { id },
      include: { draft: true },
    });

    if (!report) {
      return NextResponse.json({ error: "Report not found" }, { status: 404 });
    }

    // Build commit message from ticket info
    let commitMessage = `fix: Apply AI-generated fix to ${componentPath.split("/").pop()}`;
    let prTitle = "AI Code Fix";
    let prBody = "This PR contains an AI-generated fix.";

    if (report.draft) {
      const fields = JSON.parse(report.draft.fields) as TicketDraftFields;
      commitMessage = `fix: ${fields.title}\n\n${fields.summary}`;
      prTitle = `fix: ${fields.title}`;
      prBody = `## Summary\n${fields.summary}\n\n## Expected Behavior\n${fields.expected_behavior}\n\n## Actual Behavior\n${fields.actual_behavior}\n\n## Steps to Reproduce\n${fields.repro_steps.map((step, i) => `${i + 1}. ${step}`).join("\n")}\n\n---\n*This fix was generated by AI Code Fixer*`;
    }

    let result;

    if (createNewPR) {
      // Create a new PR with the fix
      result = await createPRWithFix(
        token,
        owner,
        repo,
        componentPath,
        fixedCode,
        prTitle,
        prBody,
        commitMessage,
        branchName
      );
    } else {
      // Apply to existing PR
      if (!prNumber) {
        return NextResponse.json(
          { error: "prNumber is required when not creating a new PR" },
          { status: 400 }
        );
      }

      result = await applyFixToPR(
        token,
        owner,
        repo,
        prNumber,
        componentPath,
        fixedCode,
        commitMessage
      );
    }

    // Update report status
    await prisma.report.update({
      where: { id },
      data: { status: "fixed" },
    });

    return NextResponse.json({
      success: true,
      commit: result.commit,
      pr: result.pr,
      message: createNewPR
        ? `Created new PR #${result.pr.number}`
        : `Applied fix to PR #${result.pr.number}`,
    });
  } catch (error) {
    console.error("Error applying fix to GitHub:", error);
    const message = error instanceof Error ? error.message : "Failed to apply fix";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
